# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: all.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='all.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tall.proto\"\x07\n\x05\x45mpty\"\'\n\x07Request\x12\x0c\n\x04iter\x18\x01 \x01(\x05\x12\x0e\n\x06req_id\x18\x02 \x01(\x05\"*\n\tPublicKey\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0e\n\x06pubKey\x18\x02 \x01(\x0c\"2\n\x05Model\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x0c\n\x04init\x18\x02 \x01(\x08\x12\x0c\n\x04iter\x18\x03 \x01(\x05\";\n\tSignature\x12\x0c\n\x04init\x18\x01 \x01(\x08\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\r\n\x05index\x18\x03 \x01(\x05\"\x8e\x01\n\rCompleteModel\x12\x0e\n\x06inputs\x18\x01 \x01(\x0c\x12\x0e\n\x06labels\x18\x02 \x01(\x0c\x12\x15\n\x05model\x18\x03 \x01(\x0b\x32\x06.Model\x12\x0c\n\x04iter\x18\x04 \x01(\x05\x12\x13\n\x0b\x63orrectProc\x18\x05 \x03(\x05\x12\x12\n\nsignatures\x18\x06 \x03(\x0c\x12\x0f\n\x07msgHash\x18\x07 \x01(\x0c\",\n\nGradHashes\x12\x10\n\x08gradHash\x18\x01 \x03(\t\x12\x0c\n\x04iter\x18\x02 \x01(\x05\"7\n\x08GradHash\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0e\n\x06g_hash\x18\x02 \x01(\x0c\x12\x0c\n\x04iter\x18\x03 \x01(\x05\"?\n\tGradients\x12\x11\n\tgradients\x18\x01 \x01(\x0c\x12\x0c\n\x04iter\x18\x02 \x01(\x02\x12\x11\n\tlipschitz\x18\x03 \x01(\x02\x32\xd4\x02\n\x14TrainMessageExchange\x12$\n\x0cGetPublicKey\x12\x06.Empty\x1a\n.PublicKey\"\x00\x12#\n\x0fGetUnifiedModel\x12\x06.Empty\x1a\x06.Model\"\x00\x12.\n\x10GetCompleteModel\x12\x08.Request\x1a\x0e.CompleteModel\"\x00\x12)\n\x0bGetOnlyHash\x12\x08.Request\x1a\x0e.CompleteModel\"\x00\x12(\n\rGetGradHashes\x12\x08.Request\x1a\x0b.GradHashes\"\x00\x12$\n\x0bGetGradHash\x12\x08.Request\x1a\t.GradHash\"\x00\x12&\n\x0cGetGradients\x12\x08.Request\x1a\n.Gradients\"\x00\x12\x1e\n\x08GetModel\x12\x08.Request\x1a\x06.Model\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=20,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iter', full_name='Request.iter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_id', full_name='Request.req_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)


_PUBLICKEY = _descriptor.Descriptor(
  name='PublicKey',
  full_name='PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='PublicKey.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pubKey', full_name='PublicKey.pubKey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=105,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Model.model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init', full_name='Model.init', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iter', full_name='Model.iter', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=157,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='Signature.init', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Signature.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='Signature.index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=218,
)


_COMPLETEMODEL = _descriptor.Descriptor(
  name='CompleteModel',
  full_name='CompleteModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='CompleteModel.inputs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='CompleteModel.labels', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='CompleteModel.model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iter', full_name='CompleteModel.iter', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correctProc', full_name='CompleteModel.correctProc', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='CompleteModel.signatures', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgHash', full_name='CompleteModel.msgHash', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=363,
)


_GRADHASHES = _descriptor.Descriptor(
  name='GradHashes',
  full_name='GradHashes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gradHash', full_name='GradHashes.gradHash', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iter', full_name='GradHashes.iter', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=409,
)


_GRADHASH = _descriptor.Descriptor(
  name='GradHash',
  full_name='GradHash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='GradHash.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='g_hash', full_name='GradHash.g_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iter', full_name='GradHash.iter', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=466,
)


_GRADIENTS = _descriptor.Descriptor(
  name='Gradients',
  full_name='Gradients',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gradients', full_name='Gradients.gradients', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iter', full_name='Gradients.iter', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lipschitz', full_name='Gradients.lipschitz', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=531,
)

_COMPLETEMODEL.fields_by_name['model'].message_type = _MODEL
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['PublicKey'] = _PUBLICKEY
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
DESCRIPTOR.message_types_by_name['CompleteModel'] = _COMPLETEMODEL
DESCRIPTOR.message_types_by_name['GradHashes'] = _GRADHASHES
DESCRIPTOR.message_types_by_name['GradHash'] = _GRADHASH
DESCRIPTOR.message_types_by_name['Gradients'] = _GRADIENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), dict(
  DESCRIPTOR = _PUBLICKEY,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:PublicKey)
  ))
_sym_db.RegisterMessage(PublicKey)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  ))
_sym_db.RegisterMessage(Model)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURE,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:Signature)
  ))
_sym_db.RegisterMessage(Signature)

CompleteModel = _reflection.GeneratedProtocolMessageType('CompleteModel', (_message.Message,), dict(
  DESCRIPTOR = _COMPLETEMODEL,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:CompleteModel)
  ))
_sym_db.RegisterMessage(CompleteModel)

GradHashes = _reflection.GeneratedProtocolMessageType('GradHashes', (_message.Message,), dict(
  DESCRIPTOR = _GRADHASHES,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:GradHashes)
  ))
_sym_db.RegisterMessage(GradHashes)

GradHash = _reflection.GeneratedProtocolMessageType('GradHash', (_message.Message,), dict(
  DESCRIPTOR = _GRADHASH,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:GradHash)
  ))
_sym_db.RegisterMessage(GradHash)

Gradients = _reflection.GeneratedProtocolMessageType('Gradients', (_message.Message,), dict(
  DESCRIPTOR = _GRADIENTS,
  __module__ = 'all_pb2'
  # @@protoc_insertion_point(class_scope:Gradients)
  ))
_sym_db.RegisterMessage(Gradients)



_TRAINMESSAGEEXCHANGE = _descriptor.ServiceDescriptor(
  name='TrainMessageExchange',
  full_name='TrainMessageExchange',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=534,
  serialized_end=874,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPublicKey',
    full_name='TrainMessageExchange.GetPublicKey',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PUBLICKEY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUnifiedModel',
    full_name='TrainMessageExchange.GetUnifiedModel',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MODEL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCompleteModel',
    full_name='TrainMessageExchange.GetCompleteModel',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_COMPLETEMODEL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOnlyHash',
    full_name='TrainMessageExchange.GetOnlyHash',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_COMPLETEMODEL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGradHashes',
    full_name='TrainMessageExchange.GetGradHashes',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_GRADHASHES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGradHash',
    full_name='TrainMessageExchange.GetGradHash',
    index=5,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_GRADHASH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGradients',
    full_name='TrainMessageExchange.GetGradients',
    index=6,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_GRADIENTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetModel',
    full_name='TrainMessageExchange.GetModel',
    index=7,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_MODEL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINMESSAGEEXCHANGE)

DESCRIPTOR.services_by_name['TrainMessageExchange'] = _TRAINMESSAGEEXCHANGE

# @@protoc_insertion_point(module_scope)
